---
name: call-CI-server
on: [push]
jobs:
  call-CI-server:
    runs-on: ubuntu-latest
    steps:
        - name: call-server
          id: ci-request
          uses: fjogeleit/http-request-action@master
          with:
            url: 'https://ciserver.geertenvink.nl/notifyPush/RunicMagic'
            method: 'POST'
            data: ${{ secrets.CISecret }}
            timeout: 60000
        - name: show-response
          run: echo ${{ steps.ci-request.outputs.response }}